import { router } from 'expo-router';
import { ArrowLeft, ArrowUp, Sparkles, UserRound } from 'lucide-react-native';
import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';

import { AppText, IconButton } from '@/components/ui';
import { colors, radii, spacing } from '@/constants/theme';
import { useDemoStore } from '@/store/use-demo-store';

type Message = { role: 'coach' | 'user'; text: string };

export default function CoachScreen() {
  const startup = useDemoStore((state) => state.startup);
  const [messages, setMessages] = useState<Message[]>([{ role: 'coach', text: `I’m looking at ${startup?.name ?? 'your startup'} with you. I can review an artifact, sharpen an assumption, or help choose your next step.` }]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  function send(text = input) {
    const message = text.trim();
    if (!message || loading) return;
    setInput(''); setLoading(true); setMessages((current) => [...current, { role: 'user', text: message }]);
    setTimeout(() => { setMessages((current) => [...current, { role: 'coach', text: 'You have a promising starting point. Your next useful move is to test one behavior with a real customer. Look for what they already do today, then update the canvas with their exact words.' }]); setLoading(false); }, 700);
  }
  return <KeyboardAvoidingView style={styles.page} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.header}><IconButton label="Close coach" icon={ArrowLeft} onPress={() => router.back()} /><View style={styles.headerCenter}><View style={styles.coachIcon}><Sparkles color={colors.white} size={16} /></View><View><AppText variant="small" style={{ fontWeight: '750' }}>Coach</AppText><AppText variant="caption" color={colors.primary}>READY TO HELP</AppText></View></View><View style={{ width: 44 }} /></View><ScrollView contentContainerStyle={styles.messages}>{messages.map((message, index) => <View key={`${message.role}-${index}`} style={[styles.messageRow, message.role === 'user' && styles.userRow]}>{message.role === 'coach' && <View style={styles.messageIcon}><Sparkles color={colors.primary} size={15} /></View>}<View style={[styles.bubble, message.role === 'user' ? styles.userBubble : styles.coachBubble]}><AppText variant="body" color={message.role === 'user' ? colors.white : colors.ink}>{message.text}</AppText></View>{message.role === 'user' && <View style={styles.messageIcon}><UserRound color={colors.inkMuted} size={15} /></View>}</View>)}{loading && <View style={styles.typing}><AppText variant="caption" color={colors.inkMuted}>Coach is thinking…</AppText></View>}</ScrollView><View style={styles.suggestions}><Pressable onPress={() => send('Review my canvas')} style={styles.suggestion}><AppText variant="caption" color={colors.primary}>Review my canvas</AppText></Pressable><Pressable onPress={() => send('What should I do next?')} style={styles.suggestion}><AppText variant="caption" color={colors.primary}>What next?</AppText></Pressable></View><View style={styles.composer}><TextInput accessibilityLabel="Message Coach" value={input} onChangeText={setInput} onSubmitEditing={() => send()} placeholder="Ask Coach anything…" placeholderTextColor={colors.inkSoft} style={styles.input} returnKeyType="send" /><Pressable accessibilityRole="button" accessibilityLabel="Send message" disabled={!input.trim() || loading} onPress={() => send()} style={[styles.send, (!input.trim() || loading) && styles.sendDisabled]}><ArrowUp color={colors.white} size={18} /></Pressable></View></KeyboardAvoidingView>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.canvas }, header: { padding: spacing.lg, paddingTop: spacing.xl, borderBottomWidth: 1, borderBottomColor: colors.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, headerCenter: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, coachIcon: { width: 32, height: 32, borderRadius: 10, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, messages: { padding: spacing.xl, gap: spacing.lg, maxWidth: 620, width: '100%', alignSelf: 'center' }, messageRow: { flexDirection: 'row', alignItems: 'flex-end', gap: spacing.sm, maxWidth: '92%' }, userRow: { alignSelf: 'flex-end' }, messageIcon: { width: 28, height: 28, borderRadius: 14, backgroundColor: colors.surfaceMuted, alignItems: 'center', justifyContent: 'center' }, bubble: { padding: spacing.md, borderRadius: 14, maxWidth: '86%' }, coachBubble: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line }, userBubble: { backgroundColor: colors.primary }, typing: { paddingLeft: 38 }, suggestions: { flexDirection: 'row', gap: spacing.sm, paddingHorizontal: spacing.lg, paddingBottom: spacing.sm }, suggestion: { paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radii.pill, backgroundColor: colors.primarySoft }, composer: { borderTopWidth: 1, borderTopColor: colors.line, padding: spacing.md, flexDirection: 'row', gap: spacing.sm, backgroundColor: colors.surface }, input: { flex: 1, minHeight: 48, borderWidth: 1, borderColor: colors.line, borderRadius: radii.md, paddingHorizontal: spacing.md, color: colors.ink, fontSize: 15 }, send: { width: 48, height: 48, borderRadius: radii.md, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, sendDisabled: { opacity: 0.4 } });
