import { router } from 'expo-router';
import { ArrowUpRight, FileText, LockKeyhole } from 'lucide-react-native';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';

import { AppText, ScreenHeader, SectionCard, StatusBadge } from '@/components/ui';
import { colors, spacing } from '@/constants/theme';
import { useDemoStore } from '@/store/use-demo-store';

export default function WorkspaceScreen() {
  const artifacts = useDemoStore((state) => state.artifacts);
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><ScreenHeader eyebrow="STARTUP WORKSPACE" title="Everything you build, in one place." description="Your startup gets clearer every time you complete a task." /><View style={styles.filterRow}><StatusBadge label="All artifacts" tone="success" /><StatusBadge label="Needs attention" /></View><View style={styles.list}>{artifacts.map((artifact) => <Pressable key={artifact.id} accessibilityRole="button" onPress={() => artifact.id === 'value-proposition' ? router.push('/artifact/value-proposition') : undefined} style={({ pressed }) => [styles.artifact, pressed && styles.pressed]}><View style={styles.artifactIcon}>{artifact.status === 'not_started' ? <LockKeyhole color={colors.inkSoft} size={18} /> : <FileText color={colors.primary} size={18} />}</View><View style={styles.artifactCopy}><AppText variant="small" style={{ fontWeight: '750' }}>{artifact.title}</AppText><AppText variant="caption" color={colors.inkMuted}>{artifact.category}</AppText></View><View style={styles.artifactMeta}>{artifact.status === 'draft' ? <StatusBadge label="Draft" tone="warning" /> : artifact.status === 'needs_review' ? <StatusBadge label="Review" tone="success" /> : artifact.status === 'complete' ? <StatusBadge label="Done" tone="success" /> : <StatusBadge label="Not started" tone="locked" />}{artifact.status !== 'not_started' && <ArrowUpRight size={17} color={colors.inkSoft} />}</View></Pressable>)}</View><SectionCard style={styles.tip}><AppText variant="caption" color={colors.primary}>A GOOD HABIT</AppText><AppText variant="headline">Build while you learn.</AppText><AppText variant="small" color={colors.inkMuted}>Every lesson leaves you with something useful for your company. Keep your artifacts honest and current.</AppText></SectionCard></ScrollView>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.canvas }, content: { padding: spacing.xl, paddingBottom: 126, maxWidth: 620, width: '100%', alignSelf: 'center' }, filterRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md }, list: { gap: spacing.sm }, artifact: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 12, padding: spacing.md, gap: spacing.md, minHeight: 72 }, pressed: { opacity: 0.72 }, artifactIcon: { width: 38, height: 38, borderRadius: 10, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, artifactCopy: { flex: 1, gap: 2 }, artifactMeta: { alignItems: 'flex-end', gap: 6 }, tip: { marginTop: spacing.xxl, gap: spacing.sm, backgroundColor: colors.surfaceMuted, borderColor: colors.surfaceMuted } });
