import { router, useLocalSearchParams } from 'expo-router';
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Lightbulb } from 'lucide-react-native';
import { ScrollView, StyleSheet, View } from 'react-native';

import { AppButton, AppText, IconButton, SectionCard } from '@/components/ui';
import { colors, spacing } from '@/constants/theme';

export default function LessonScreen() {
  const { lessonId } = useLocalSearchParams<{ lessonId: string }>();
  const isInterview = lessonId === 'customer-interviews';
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><View style={styles.top}><IconButton label="Go back" icon={ArrowLeft} onPress={() => router.back()} /><AppText variant="caption" color={colors.inkMuted}>LESSON 1 OF 3</AppText><View style={{ width: 44 }} /></View><View style={styles.meta}><View style={styles.lessonIcon}><Lightbulb color={colors.primary} size={22} /></View><View style={styles.metaText}><AppText variant="caption" color={colors.primary}>VALIDATE</AppText><View style={styles.time}><Clock3 color={colors.inkMuted} size={14} /><AppText variant="caption" color={colors.inkMuted}>4 min lesson</AppText></View></View></View><AppText variant="display" style={styles.title}>{isInterview ? 'Ask better customer questions.' : 'Turn beliefs into tests.'}</AppText><AppText variant="body" color={colors.inkMuted} style={styles.lead}>{isInterview ? 'The goal of an interview is to understand someone’s current behavior, not to convince them your idea is good.' : 'Every startup idea begins as a set of beliefs. The fastest way forward is to name the belief that could make the whole idea wrong.'}</AppText><View style={styles.section}><AppText variant="headline">The useful shift</AppText><SectionCard style={styles.callout}><CheckCircle2 color={colors.primary} size={19} /><View style={{ flex: 1, gap: 4 }}><AppText variant="small" style={{ fontWeight: '750' }}>{isInterview ? 'Ask about the past, not the future.' : 'A vague belief cannot be validated.'}</AppText><AppText variant="small" color={colors.inkMuted}>{isInterview ? '“Tell me about the last time…” gives you evidence. “Would you use…” gives you a polite guess.' : '“People need help” becomes useful when you define who, what they do today, and what evidence would change your mind.'}</AppText></View></SectionCard></View><View style={styles.section}><AppText variant="headline">Remember</AppText><View style={styles.bullets}><Bullet text={isInterview ? 'Listen for workarounds and friction.' : 'Write one belief at a time.'} /><Bullet text={isInterview ? 'Do not pitch during discovery.' : 'Choose the belief with the most risk.'} /><Bullet text={isInterview ? 'Capture exact words and behaviors.' : 'Decide what evidence would prove you wrong.'} /></View></View><View style={styles.bottom}><AppButton label="Try it now" icon={ArrowRight} onPress={() => router.push(`/task/${isInterview ? 'prepare-interview' : 'write-assumption'}`)} /><AppText variant="caption" color={colors.inkSoft} style={styles.footer}>You will leave this lesson with a real startup artifact.</AppText></View></ScrollView>;
}

function Bullet({ text }: { text: string }) { return <View style={styles.bullet}><View style={styles.bulletDot} /><AppText variant="body" style={{ flex: 1 }}>{text}</AppText></View>; }

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.canvas }, content: { padding: spacing.xl, paddingBottom: spacing.xxxl, maxWidth: 620, width: '100%', alignSelf: 'center' }, top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.xxl }, meta: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, lessonIcon: { width: 48, height: 48, borderRadius: 14, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, metaText: { gap: 4 }, time: { flexDirection: 'row', alignItems: 'center', gap: 5 }, title: { marginTop: spacing.xl, maxWidth: 450 }, lead: { lineHeight: 25, marginTop: spacing.md, maxWidth: 500 }, section: { gap: spacing.md, marginTop: spacing.xxxl }, callout: { flexDirection: 'row', gap: spacing.md, backgroundColor: colors.primarySoft, borderColor: '#C7E3D9' }, bullets: { gap: spacing.md }, bullet: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, bulletDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.primary }, bottom: { marginTop: spacing.xxxl }, footer: { textAlign: 'center', marginTop: spacing.md } });
